# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4cab3ae1c49c7f346fc0a6e3120852400660baf636de50dc6ff86a8a75cf83084d6d16fd98c44095f0bfe03d35710d622d1ec3a86df6fcb8926d3c6f1a78b5d

test:
  secret_key_base: d251a7f2644ac05879d83a798a09e97280c4375c085d642d3e41b69a212d6091625b3b0e7d88cdef4e088010b3f7eb3628be90d811423bf6562f960de3ae6cf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
